version: '3.8'

services:
  automanager-gateway:
    container_name: automanager-gateway
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - EMPRESA_SERVICE_URL=http://empresa-service:8081
    depends_on:
      - empresa-service

  empresa-service:
    container_name: empresa-service
    build:
      context: ./empresas
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

networks:
  default:
    name: automanager-network
