### Cadastrar uma nova empresa
POST http://localhost:8080/empresa/cadastrar
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "id": 2,
  "razaoSocial": "Empresa 1",
  "nomeFantasia": "Empresa 1",
  "cadastro": "2025-01-01",
  "endereco": {
    "id": 3,
    "estado": "SP",
    "cidade": "São Paulo",
    "bairro": "Jardim Paulista",
    "rua": "Rua das Flores",
    "numero": "123",
    "codigoPostal": "04101-300",
    "informacoesAdicionais": "Apto 101"
  },
  "telefones": [
    {
      "id": 4,
      "numero": "1234567892",
      "ddd": "11"
    }
  ]
}

### Obter todos os documentos
GET http://localhost:8080/empresa/listar
Authorization: Bearer {{JWT}}

### Obter um documento específico
GET http://localhost:8080/empresa/3
Authorization: Bearer {{JWT}}
Content-Type: application/json

### Atualizar um documento
PUT http://localhost:8080/empresa/atualizar
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "id": 3,
  "razaoSocial": "razaoSocial 321"
}

### Excluir um documento
DELETE http://localhost:8080/empresa/excluir
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "id": 3
}
